Homework 4: Add bastion host to GCP
Otus-DevOps-2018-02/sectronov_infra pull request #3
Opened 2018-03-18 22:17 UTC by sectronov

# Выполнено ДЗ № 4

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - В GCP добавлены 2 VM, одна с внешнем IP-адресом (bastion), вторая только со внутренним (someinternalhost)
 - Найден способ подключения к someinternalhost через bastion по ssh в одну строчку
 - На хосте bastion через pritunl запущен VPN
 - Настроены правила файрвола в GCP для работы VPN
 - Проверен доступ к someinternalhost при запущенном VPN

## Как запустить проект:
 - Для подключения использовать `bastion_IP = 35.205.140.104, someinternalhost_IP = 10.132.0.3`
 - Открыть `cloud-bastion.ovpn` клиентом OpenVPN
 - Подключиться к VPN пользователем test и паролем из ДЗ

## Как проверить работоспособность:
 - Выполнить `ssh appuser@10.132.0.3`, если подключение успешно, то всё ок

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-03-22 10:13 UTC, vitkhab requested changes
Прошу удалить лишние строчки из `setupvpn.sh`. Понятно ли почему они лишние?

В остальном все хорошо. Классное описание. Выполнил доп. задание. Молодец!

2018-03-22 10:13 UTC, vitkhab commented on setupvpn.sh
> +cat <<EOF> setupvpn.sh
Лишняя строчка

2018-03-22 10:13 UTC, vitkhab commented on setupvpn.sh
> +EOF
Тоже лишняя строчка

2018-03-23 04:23 UTC, glaznaj commented
@vitkhab Спасибо! Не заметил 🙃

2018-03-30 13:33 UTC, vitkhab approved these changes
Молодец! Спасибо, что исправил

2018-03-30 15:19 UTC, merged